Containerfile
README.md

Before usage expands and more services get added, set the baseline of all non-default services being disabled by default.
The significant change is this PR disables `cockpit.service` where we'd previously enabled it. This prevents it from starting by default and downloading the cockpit podman image, where it may not be desired. Users who wish to use it can enable as they would any other service.
Already, `tailscaled.service` and `docker.service` were disabled by default, though `docker.socket` was enabled by default.
`docker.socket` is now specifically disabled with an explanation in README.

feat: disable non-default services by default

---

Containerfile
etc/systemd/system/ucore-paths-provision.service
etc/systemd/ucore-paths-provision.conf
post-install.sh
usr/sbin/ucore-paths-provision.sh

for directories that are lost due to OCI images not allowing them in /var, etc, this provides a config file which can be used to define the set of dirs (with mode) which should be created, and restorecon on them
only exec mkdir/restorecon if the directory is absent when service runs

feat: provision required directories at boot

---

README.md
etc/systemd/system/ucore-paths-provision.service
examples/ucore-autorebase.butane

Provide docs and a sample butane file which has been tested to provide a means to autorebase into uCore as part of a new CoreOS installation.
Resolves #3

feat: provide example to autorebase to uCore

---

.github/workflows/build.yml

Workaround for #21 to enable stable image builds even when testing image builds fail.

fix: enable stable builds despite testing failure

---

.github/workflows/build.yml
zfs/Containerfile

Fixes #21 a few hours ahead of time since zfs 2.1.10 has been released but release-monitoring.org is not updated yet. Since we just use github releases for zfs anyway, may as well check them directly.

chore: directly use github for zfs version

---

zfs/Containerfile

I investigated continued instability of ZFS builds thinking it could be related to the F38 release. It may have been in a manner of speaking. But I discovered the method of using a Fedora image as a builder was more complex than needed and was the actual culprit.
Switched to using CoreOS image itself as the builder, which primarily required using rpm-ostree (instead of dnf) and the hack to allow alternatives to function (mkdir -p /var/lib/alternatives).

fix: stabilize zfs builds

---

main/Containerfile
main/packages.json

On Fedora 38 (testing) the `docker-compose` RPM is no longer installable. It depends on `python3-dockerpty` which is not maintained and may not be added to the Fedora 38 repos. I've replaced the old python version which was installing from repos with a static binary sourced from docker's official container image for the tool.

fix: change docker-compose installation

---

hci/Containerfile
hci/build.sh
hci/packages.json

As of F38(new fcos:testing), nfs-utils and nfs-utils-coreos now conflict, where previously they would install at same time despite providing the same files. 
This fixes the problem by removing nfs-utils-coreos and ensuring the installation of nfs-utils.
Switched back to the build.sh/packages.json model for this despite larger image layers as it makes build scripts cleaner.
Fixes: #31

fix: swap nfs-utils-coreos for nfs-utils

---

main/Containerfile
zfs/Containerfile

I had assumed the testing repos were enabled by default on the FCOS testing stream, but it seems they are not. This change enables them, but only after ensuring they are not already enabled. This should correct build failures which occur on testing when packages are being worked on and in testing repos but not yet moved to stable.

fix: enable testing repos on testing stream

---

README.md
main/packages.json

We inherited the removal of toolbox, but I'd rather include to retain CoreOS familiarity unless there is a compelling reason to remove.
fixes: #20

feat: restore toolbox

---

README.md
main/post-install.sh

Fedora dropped the DefaultTimeoutStop in systemd to 45s. This change also applies to FCOS. Instead of setting our own arbitrary value of 60s, use the default. Also add a message to README addressing the primary concern of this change, slow VM shutdowns in libvirtd.

feat: use upstream DefaultTimeoutStop

---

.github/workflows/build.yml

we've had a few days of failed builds due to a new release candidate, pre-release being in the github releases which I wasn't parsing properly.
This change:
1. parses the name properly
2. ignores pre-releases so we'll only attempt stable zfs release builds

fix: ignore github prereleases for zfs

---

main/Containerfile
main/build.sh

This simplifies the Containerfile and moves preparation logic for zfs (and future nvidia) into the build.sh script for simpler scripting. Also adds rpmfusion repos and no longer deletes the tailscale repo.

refactor: reorganize build scripts add repos

---

README.md
hci/packages.json

Had a user bring this up in Discord chat. It seemed odd to me that Atheros wifi would work out of the box but not Intel.
Including in `ucore-hci` for hardware enablement, but not in `ucore` to keep with the theme of minimal base/VM image.

feat: add intel wifi firmware

---

README.md
hci/Containerfile
hci/files/usr/etc/udev/rules.d/50-usb-realtek-net.rules

This has been added to Universal Blue for desktops, but is also useful for ucore users.

feat: add udev rules for 2.5G realtek usb

---

hci/build.sh
main/build.sh

Changes the build.sh logic for packages.json so one can remove (exclude) a dependent package which is installed by an included package. Also handle the case where an include/exclude combo results in an override replace operation.

refactor: ensure packages.json override/replace works

---

main/post-install.sh

Had this problem on the desktop universal blue nvidia images also. The systemd service preset is not enough to ensure a service is enabled after rebasing to an image containing it. So the service must be explicitly enabled.
Fixes: #102

fix: enable ublue-nvctk-cdi by default for nvidia images

---

README.md
fedora-coreos/install.sh
main/install.sh

With zfs 2.1.x, this happened automatically. Though unclear why, it no longer seems to occur when installing the zfs 2.2.x RPMs in a container build (it does still work automatically on a non image-based Fedora system).
Manually running depmod, as in this commit, ensures the 2.2.x kmods load as expected.
Fixes: #88

fix: run depmod after installing ZFS RPMs

---

README.md
main/Containerfile
main/install.sh

Add the new package from `ucore-kmods` which includes the signing key. This enables a user to import the signing key as a MOK using:
sudo mokutil --import /etc/pki/akmods/certs/akmods-ublue.der
Closes #82

feat: add package with secure boot public signing key

---

.github/workflows/build.yml

I intentionally stopped publishing a `:latest` tag back on April 1st. It was not intended to be an April Fool's joke, but rather a cleanup to best practices of not using that tag. However, the old images did not expire, so the old `:latest` continues to exist, confusing both users and our website's image discovery code.
I suppose it turned out to be a long lived April Fool's joke after all!
This resumes the publishing of the tag, ensuring it matches the `:stable` tag, and only on the `ucore` image. There will be no `:latest` for nvidia, zfs or testing images, nor `fedora-coreos` or `ucore-hci`.

chore(ci): resume use of latest tag for stable image

---

.github/workflows/reusable-build.yml

this was broken by adding retry as it changes output structure.

chore(ci): fix image signing after adding retry

---

ucore/packages.json

Add NetworkManager-wifi for a better wifi management experience.
---
Based on https://github.com/ublue-os/ucore/pull/139 for convenience.
See: https://github.com/ublue-os/ucore/issues/138
See: https://github.com/coreos/fedora-coreos-tracker/issues/862

feat: ucore/packages.json: Add NetworkManager-wifi

---

README.md
ucore/Containerfile

Some users had noticed that `docker-compose` was not usable as a plugin (eg, `docker compose`). This fixes that by installing it the way moby does upstream, plus adds `docker-buildx`. Both are versioned now rather than being `latest`, and version matched to the moby release.
Note: this is a minor downgrade of `docker-compose` from `v2.26.1` to `v2.24.7`.
As of this writing, FCOS next is still on moby 24.0.5. 
Some details on versions:
- https://fedoraproject.org/coreos/release-notes?arch=x86_64&stream=testing
- https://github.com/docker/buildx/releases
- https://github.com/docker/compose/releases
Closes: #141

feat: install docker-compose as cli plugin, add buildx

---

examples/ucore-autorebase.butane

1. I moved the logic from `ucore-autorebase.sh` into the service itself, to minimize leftover files.
2. I also added another service to rebase to the signed image, after the initial rebase-and-reboot, just like [blue-build/template](https://github.com/blue-build/template) recommends in the README.
3. I ripped out `RemainAfterExit=yes` since i couldn't figure out why it was needed.
4. I added `--bypass-driver` to the rebase commands to bypass this error: (building on ucore-minimal)
```
Apr 25 19:50:33 localhost.localdomain rpm-ostree[1846]: error: Updates and deployments are driven by Zincati (zincati.service)
Apr 25 19:50:33 localhost.localdomain rpm-ostree[1846]: See Zincati's documentation at https://github.com/coreos/zincati
Apr 25 19:50:33 localhost.localdomain rpm-ostree[1846]: Use …
```

feat: Added rebasing to a signed image

---

ucore/packages.json

CoreOS testing stream has already moved to Fedora 40, which sadly swapped wget for wget2 which was not an actual replacment.
See issues:
- https://gitlab.com/gnuwget/wget2/-/issues/661
- https://github.com/rockdaboot/wget2/issues/314
Given the current situation, this package will be removed from ucore until further notice.

fix: remove wget/wget2 package

---

ucore/install-ucore-hci.sh

For over a week, the libvirt-client package has required a version of gnu-tls not available for install. This fixes by granting access to the coreos pool repo which caches versions of packages used in FCOS even if they are no longer present in other Fedora repos.

fix: add coreos pool repo to mitigate dependancy build issue

---

ucore/install-ucore.sh

mergerfs chagned naming on their RPMs to be more specific.
This catches up to that change.
Fixes: #157

fix: use fedora release for mergerfs install

---

ucore/install-ucore-hci.sh
ucore/install-ucore-minimal.sh

Two previous changes had added the fedora-coreos-pool.repo to mitigate build issues with slightly older CoreOS RPM dependencies no longer being available during builds of uCore. This was done without any prioritization changes, and initially worked fine as Fedora 40 was the newest release in the repo. Now it seems Fedora 41 packages are making their way into the uCore images, which was NOT intended and not desired. This removes that repo.
If it is ever needed again, will need to investigate deprioritizing so normal repos are used except for missing packages.
Fixes: #174
Relates: #163
Relates: #167

fix: do not install pre-release packages

---

ucore/post-install-ucore-minimal.sh
ucore/system_files/usr/lib/systemd/system/gssproxy-workaround.service
ucore/system_files/usr/lib/systemd/system/libvirt-workaround.service
ucore/system_files/usr/lib/systemd/system/swtpm-workaround.service
ucore/system_files/usr/lib/tmpfiles.d/gssproxy-workaround.conf
ucore/system_files/usr/lib/tmpfiles.d/libvirt-workaround.conf
ucore/system_files/usr/lib/tmpfiles.d/swtpm-workaround.conf

Fixes the selinux issues which have been reported to cause issues with gssproxy as well as the libvirt and swtpm issues.

fix: various selinux issues

---

.github/workflows/reusable-build.yml

This moves the version check for zfs/nvidia akmods images into distict, conditional blocks, which no longer blocks ALL testing image builds if those versions happen to be out of sync.

chore(ci): don't block non-zfs/non-nivdia testing builds

---

.github/workflows/build-stable.yml
.github/workflows/build-testing.yml

I have noticed the ucore builds run long after akmods, which leaves room for drift on kernel versions.
Running these 45 and 50 minutes after akmods to keep it closely connected.

chore(ci): update cron schedule to follow akmods

---

ucore/packages.json

This removes the cockpit-pcp package as it's no longer required. The functionality was implemented within cockpit-bridge which is already installed.
See: https://cockpit-project.org/blog/cockpit-326.html
Fixes builds of ucore/ucore-hci.

feat: updated cockpit-bridge obsoletes cockpit-pcp

---

README.md

Relates: https://github.com/ublue-os/image-template/issues/3

docs: add image-template link in DIY section

---

.github/workflows/build-stable.yml
.github/workflows/build-testing.yml

This is a safety measure to avoid upgrading to kernel 6.11.5 which will break tailscale status and likely cause bug reports.
CoreOS images updated stable to F41 this morning... however, it now uses kernel 6.11.5 which has a known bug which (IMHO is a pretty bad typo) breaks tailscale status reporting https://github.com/tailscale/tailscale/issues/13863 (Note: I do believe tailscale connectivity still works on this kernel, only status reporting is broken.)

chore: temporarily pause stable scheduled builds

---

.github/workflows/build-stable.yml
.github/workflows/reusable-build.yml
README.md

Needs coreos-stable akmods 41 building

chore(ci): Use kernel-cache for kernel-version

---

fedora-coreos/install.sh
ucore/install-ucore-minimal.sh

There is a difference in how Bluefin and uCore run depmod, so I'm trying their method as that seems to at least not hurt, and may resolve this.
I did test a locally built image with these changes in a VM. It helped, but then I reverted them and I couldn't reproduce the problem at all, so the results seemed positive but inconclusive.
Relates: #210

fix: possible fix for apparent ZFS depmod fail

---

README.md
ucore/install-ucore.sh

Instead of documenting its absence, let's ensure mergerfs is present!
This isn't installed via RPM but at least it's there.
Fixes: #214

fix: restore mergerfs in f41

---

ucore/github-release-install.sh

This copies the fix from ublue-os/main#571 to ensure that the github release install script fails properly when nothing matches the filter.
The bug fixed by this also relates to ublue-os/ucore#214 since that kind of bug report will be caught by build failures in the future, thanks to this fix.
Thanks to @bcook254 for the solution in the ublue-os/main#571 PR.

fix: github release install silently fails if no urls found

---

README.md

As shipped, the `/var/home/core/.config` directory is empty. Need to create the `systemd` and `user` direcotries before the cp command can succeed.

docs: create parent dirs in README.md

---

.github/workflows/build-stable.yml
.github/workflows/build-testing.yml

Small tweak, but we don't need to spend builders for no reason when only markdown changes.

chore(ci): don't run ci for markdown changes

---

ucore/install-ucore.sh

This is a second fix for #214, since the first fix was more of a workaround. But since upstream build an F41 RPM package in reponse to our bug report, we can use that now, which fixes the concern reported by users of mergerfs.
Fixes: #214

fix: restore mergerfs RPM install

---

examples/ucore-autorebase.butane

Minor fix on the example autorebase butane file. I think that 
```
ConditionPathExists=!/etc/ucore-autorebase/verified
```
was intended to be 
```
ConditionPathExists=!/etc/ucore-autorebase/signed
```
Not a big deal since it won't impact the end result as `/etc/ucore-autorebase/verified` does not exist as well. But `/etc/ucore-autorebase/verified` would be "more correct" since that is the file being created on successful run.
I noticed this as I took the example and modified it for my custom ucore image and accidentally introduced a bug in my butane file as a result.

fix: correct the filename for ConditionPathExists on ucore-signed-autorebase.service

---

README.md

This hopefully helps new users. :)
I also added the missing quotes to `semanage fcontext` lines, which I encounter on copy-paste.

docs: Add install example and fix fcontext commands

---

.github/workflows/reusable-build.yml
fedora-coreos/Containerfile
ucore/Containerfile

FCOS 42.20250410.3.1contains kernel 6.14.0-63 a rawhide kernel. We want to delay this release and the only good way at this time is to delay the stable update by one cycle.
This forcibly downgrades a build from 42.20250410.3.1 to 41.20250331.3.0 until stable updates to the next release (which should include kernel 6.14.3-200.

chore: hack a forced delay on stable F42

---

README.md
ucore/github-release-install.sh
ucore/install-ucore-minimal.sh
ucore/install-ucore.sh
ucore/packages.sh

docs: announced Fedora 42 for uCore
also remove incorrect reference to 6.14.0 kernel as "rawhide".
fix: ensure "excluded" packages are removed before installing
In the recent change to dnf from rpm-ostree, the packages.sh script
had a bug introduced which didn't show until F42. Excluded packages need
to be removed before installing packages, in case there is a conflict
between an existing and to be installed package.

fix: remove excluded packages and announce Fedora 42 for uCore

---

ucore/Containerfile

It's past time to update buildx and compose plugins.
This brings them in sync with the version of moby-engine which has shipped on Fedora 42 CoreOS since 42.20250410.

chore: update docker buildx/compose plugins

---

ucore/Containerfile

There was a regression as part of the refactor that hacked/botched a
workaround for `semodule install`.
Related-to: https://github.com/ublue-os/ucore/pull/253
Fixes: https://github.com/ublue-os/ucore/issues/258

fix: System files copy of `/etc` dir

---

ucore/install-ucore-minimal.sh

Avoids errors when kernel-modules-extra (or other listed packages) is not installed.
This keeps the package in the removal list in case it returns in the future.

fix: only remove kernel package if installed

---

ucore/post-install-ucore-minimal.sh
ucore/system_files/etc/ssh/sshd_config.d/90-enable-localhost-passwords.conf

Instead of enabling SSH password login on any network, this now restricts password login to localhost (both IPv4 and IPv6).
This is the minimum requirement to enable Cockpit logins.
Closes: #275

feat: more secure Cockpit login

---

ucore/post-install-ucore-minimal.sh

Fedora CoreOS' Zincati now supports OCI and a service was added to encourage users to migrate to OCI.
As uCore is already OCI based, this warning is not applicable to uCore users.
Disable the warning.
Closes: #282

feat: don't warn about OCI migration
